# Generated by Django 6.1 on 2026-10-02 20:21

import django.db.models.deletion
import tierlist.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='My tier list', max_length=100)),
                ('palette', models.JSONField(default=tierlist.models.default_tierlist_palette)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#e85d3f', max_length=7)),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.tierlist')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1)),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.tierlist')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.category')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.choice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'choice'), name='unique_category_choice')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0.1)), name='weight_gte_point_one'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('weight__lte', 1)), name='weight_lte_one'),
        ),
    ]
