# Generated by Django 6.0.7 on 2026-08-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='weight_gte_zero'), models.CheckConstraint(condition=models.Q(('weight__lte', 1)), name='weight_lte_one')],
            },
        ),
        migrations.CreateModel(
            name='CategoryChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.category')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.choice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'choice'), name='unique_category_choice')],
            },
        ),
    ]
