# Generated by Django 6.1 on 2026-09-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='weight_gte_zero',
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.RunSQL(
            sql="UPDATE tierlist_category SET weight = 0.1 WHERE weight < 0.1",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0.1)), name='weight_gte_point_one'),
        ),
    ]
