# Generated by Django 6.0.7 on 2026-09-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0003_tierlist_category_tier_list_choice_tier_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
