# Generated by Django 6.0.7 on 2026-10-01 16:51

import tierlist.models
from django.db import migrations, models


def assign_existing_color_slots(apps, schema_editor):
    Choice = apps.get_model('tierlist', 'Choice')
    for tier_list_id in Choice.objects.order_by().values_list('tier_list_id', flat=True).distinct():
        choices = Choice.objects.filter(tier_list_id=tier_list_id).order_by('order', 'pk')
        for color_slot, choice in enumerate(choices):
            Choice.objects.filter(pk=choice.pk).update(color_slot=color_slot)


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0004_alter_category_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color_override',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='choice',
            name='color_slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tierlist',
            name='palette',
            field=models.JSONField(default=tierlist.models.default_tierlist_palette),
        ),
        migrations.RunPython(assign_existing_color_slots, migrations.RunPython.noop),
    ]
