# Generated by Django 6.0.7 on 2026-10-01 17:58

from django.db import migrations, models


def copy_existing_choice_colors(apps, schema_editor):
    Choice = apps.get_model('tierlist', 'Choice')
    TierList = apps.get_model('tierlist', 'TierList')
    palettes = dict(TierList.objects.values_list('pk', 'palette'))
    for choice in Choice.objects.all().iterator():
        palette = palettes.get(choice.tier_list_id) or ['#e85d3f']
        override = choice.color_override
        if isinstance(override, str) and len(override) == 7 and override.startswith('#'):
            color = override
        else:
            color_slot = choice.color_slot or 0
            color = palette[color_slot % len(palette)]
        Choice.objects.filter(pk=choice.pk).update(color=color)


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0005_choice_color_override_choice_color_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=models.CharField(default='#e85d3f', max_length=7),
        ),
        migrations.RunPython(copy_existing_choice_colors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='choice',
            name='color_override',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='color_slot',
        ),
    ]
